version: '3.8'

networks:
     test-network:
         driver: bridge
         ipam:
             driver: default
             config:
                 - subnet: "172.50.0.0/16"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "qweqwe123"
    ports:
      - "5432:5432"
    networks:
         - test-network

  php-fpm:
    build:
      context: ./services/php_8.2
      dockerfile: Dockerfile
    container_name: ${COMPOSE_APP_NAME}-php-fpm
    restart: always
    tty: true
    working_dir: /var/www/${COMPOSE_APP_NAME}
    volumes:
      - ${APP_PATH}/:/var/www/${COMPOSE_APP_NAME}
      - ./docker/services/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - postgres
    networks:
         - test-network

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: ${COMPOSE_APP_NAME}-nginx
    restart: always
    tty: true
    ports:
      - ${APP_PORT_MAP}
    working_dir: /var/www
    volumes:
      - ${APP_PATH}/:/var/www/${COMPOSE_APP_NAME}
    networks:
         - test-network


